### ISSUE TITLE
MoleculeKit name

### ISSUE THREAD

**Issue by stefdoerr** [divelab/MoleculeX#3]
Hi, I just wanted to point out that there will be some strong confusion between our libraries especially since we are working in very similar fields
https://github.com/Acellera/moleculekit/
https://pypi.org/project/moleculekit/
https://software.acellera.com/docs/latest/moleculekit/

Our MoleculeKit does not directly contain machine learning methods but it is used for machine learning, especially the voxelization part is already used in publications such as [DeepSite](https://pubmed.ncbi.nlm.nih.gov/28575181/), [Kdeep](https://pubs.acs.org/doi/10.1021/acs.jcim.7b00650) and a few other publications.

In any case, the naming confusion I think is not convenient for either of our groups so I just wanted to point it out in case you were not aware of the naming overlap.

**Comment by mengliu1998** [comment]
Thanks for your reminder. We have renamed and reorganized our project.
