### ISSUE TITLE
Could you provide trained models? 

### ISSUE THREAD

**Issue by w29593617** [divelab/MoleculeX#4]
Hi there, 

I find the training phase costs too much time for me, like 1+ hour per epoch. Could you please provide the trained models?

Regards, 
Josh

**Comment by lyzustc** [comment]
Hi Josh,

For sequence methods, we have provided the trained models. You can download it through the links offered in the README.md file.

**Comment by mengliu1998** [comment]
Hi Josh,

We also provide the trained models for our GNN method. Please refer to https://github.com/divelab/MoleculeX/tree/master/AdvProp/graph/trained_models and https://drive.google.com/drive/folders/1Y1gP4AZyFhfXiWLR16jlPoKIbhImyQFc. Thank you.

**Comment by w29593617** [comment]
> Hi Josh,
> 
> We also provide the trained models for our GNN method. Please refer to https://github.com/divelab/MoleculeX/tree/master/AdvProp/graph/trained_models and https://drive.google.com/drive/folders/1Y1gP4AZyFhfXiWLR16jlPoKIbhImyQFc. Thank you.

@mengliu1998 @lyzustc Thank you for your reply! Gonna close this issue.
